会う: '会った'
開く: '開いた'
開ける: '開けた'
上げる: '上げた'
遊ぶ: '遊んだ'
あびる: 'あびた'
洗う: '洗った'
ある: 'あった'
歩く: '歩いた'
言う: '言った'
行く: '行った'
要る: '要った'
いる: 'いた'
入れる: '入れた'
歌う: '歌った'
生まれる: '生まれた'
売る: '売った'
起きる: '起きた'
置く: '置いた'
教える: '教えた'
押す: '押した'
覚える: '覚えた'
泳ぐ: '泳いだ'
降りる: '降りた'
終わる: '終わった'
買う: '買った'
返す: '返した'
帰る: '帰った'
かかる: 'かかった'
書く: '書いた'
かける: 'かけた'
貸す: '貸した'
かぶる: 'かぶった'
借りる: '借りた'
消える: '消えた'
聞く: '聞いた'
切る: '切った'
着る: '着た'
曇る: '曇った'
消す: '消した'
答える: '答えた'
困る: '困った'
差す: '差した'
閉まる: '閉まった'
締める: '締めた'
閉める: '閉めた'
知る: '知った'
吸う: '吸った'
住む: '住んだ'
座る: '座った'
出す: '出した'
立つ: '立った'
頼む: '頼んだ'
食べる: '食べた'
使う: '使った'
疲れる: '疲れた'
着く: '着いた'
作る: '作った'
つける: 'つけた'
勤める: '勤めた'
出かける: '出かけた'
できる: 'できた'
出る : '出た'
飛ぶ: '飛んだ'
止まる: '止まった'
取る: '取った'
撮る: '撮った'
無くす: '無くした'
習う: '習った'
並ぶ: '並んだ'
並べる: '並べた'
なる: 'なった'
寝る: '寝た'
上る: '上った'
飲む: '飲んだ'
乗る: '乗った'
入る: '入った'
はく: 'はいた'
始まる: '始まった'
走る: '走った'
働く: '働いた'
話す: '話した'
貼る: '貼った'
引く: '引いた'
段く: '段いた'
曲がる: '曲がった'
待つ: '待った'
磨く: '磨いた'
見せる: '見せた'
見る: '見た'
持つ: '持った'
休む: '休んだ'
やる: 'やった'
呼ぶ: '呼んだ'
読む: '読んだ'
分かる : '分かった'
忘れる: '忘れた'
渡る : '渡った'