会う : '会える'
開く : '開ける'
開ける : '開けられる'
上げる : '上げられる'
遊ぶ : '遊べる'
あびる : 'あびられる'
洗う : '洗える'
歩く : '歩ける'
言う : '言える'
行く : '行ける'
要る : '要れる'
いる : 'いられる'
入れる : '入れられる'
歌う : '歌える'
生まれる : '生まれられる'
売る : '売れる'
起きる : '起きられる'
置く : '置ける'
教える : '教えられる'
押す : '押せる'
覚える : '覚えられる'
泳ぐ : '泳げる'
降りる : '降りられる'
終わる : '終われる'
買う : '買える'
返す : '返せる'
帰る : '帰れる'
かかる : 'かかれる'
書く : '書ける'
かける : 'かけられる'
貸す : '貸せる'
かぶる : 'かぶられる'
借りる : '借りられる'
消える : '消えられる'
聞く : '聞ける'
切る : '切られる'
着る : '着れる'
曇る : '曇れる'
消す : '消せる'
答える : '答えられる'
困る : '困れる'
差す : '差せる'
閉まる : '閉まれる'
締める : '締められる'
閉める : '閉められる'
知る : '知れる'
吸う : '吸える'
住む : '住める'
座る : '座れる'
出す : '出せる'
立つ : '立てる'
頼む : '頼める'
食べる : '食べられる'
使う : '使える'
疲れる : '疲れられる'
着く : '着ける'
作る : '作れる'
つける : 'つけられる'
勤める : '勤められる'
出かける : '出かけられる'
出る  : '出られる'
飛ぶ : '飛べる'
止まる : '止まれる'
取る : '取れる'
撮る : '撮れる'
無くす : '無くせる'
習う : '習える'
並ぶ : '並べる'
並べる : '並べられる'
なる : 'なれる'
寝る : '寝られる'
上る : '上れる'
飲む : '飲める'
乗る : '乗れる'
入る : '入れる'
はく : 'はける'
始まる : '始まれる'
走る : '走れる'
働く : '働ける'
話す : '話せる'
貼る : '貼れる'
引く : '引ける'
段く : '段ける'
曲がる : '曲がれる'
待つ : '待てる'
磨く : '磨ける'
見せる : '見せられる'
見る : '見られる'
持つ : '持てる'
休む : '休める'
やる : 'やれる'
呼ぶ : '呼べる'
読む : '読める'
分かる  : '分かれる'
忘れる : '忘れられる'
渡る  : '渡れる'